import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from "expo-audio";
import { Platform } from "react-native";

/**
 * Short UI sounds (generated by scripts/generate-sounds.py). Playback only: call `playSound` from
 * src/utils/haptics.ts, which owns the on/off preference. Nothing here ever throws.
 */
export type SoundName = "add" | "update" | "settle" | "delete" | "signIn";

/* eslint-disable @typescript-eslint/no-require-imports -- Metro bundles audio assets via require(). */
const SOURCES: Record<SoundName, number> = {
  add: require("../../assets/sounds/add.wav"),
  update: require("../../assets/sounds/update.wav"),
  settle: require("../../assets/sounds/settle.wav"),
  delete: require("../../assets/sounds/delete.wav"),
  signIn: require("../../assets/sounds/signin.wav"),
};
/* eslint-enable @typescript-eslint/no-require-imports */

/** The same sound again within this window is dropped, so a double-fired call plays once. */
const REPEAT_GUARD_MS = 250;

const players: Partial<Record<SoundName, AudioPlayer>> = {};
const lastPlayed: Partial<Record<SoundName, number>> = {};

// Load every player once, when this module is first imported (at app start, via haptics.ts), so
// playback is instant.
if (Platform.OS !== "web") {
  try {
    // Mix with the user's music (never pause or duck it), and stay quiet in silent mode. On Android
    // `playsInSilentMode: false` also suppresses playback in vibrate/silent ringer mode. Volume
    // follows the media stream.
    setAudioModeAsync({
      interruptionMode: "mixWithOthers",
      playsInSilentMode: false,
      shouldPlayInBackground: false,
      allowsRecording: false,
    }).catch(() => {});
    for (const name of Object.keys(SOURCES) as SoundName[]) {
      try {
        players[name] = createAudioPlayer(SOURCES[name]);
      } catch {
        // This one stays silent; the haptic still fires.
      }
    }
  } catch {
    // Audio unavailable: every sound is silent.
  }
}

export function playSound(name: SoundName): void {
  try {
    const player = players[name];
    if (!player) return;
    const now = Date.now();
    if (now - (lastPlayed[name] ?? 0) < REPEAT_GUARD_MS) return;
    lastPlayed[name] = now;
    // A finished player rests at its end, so rewind first (iOS and Android both need it).
    player
      .seekTo(0)
      .then(() => player.play())
      .catch(() => {});
  } catch {
    // Never let a sound break the action it decorates.
  }
}
